version: '3'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5423:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart

  tippecanoe:
    build:
      context: .
      dockerfile: ./containers/tippecanoe/Dockerfile
    user: root
    environment:
      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
    volumes:
      - "/tmp/geojson:/data_tiles"

  importer:
    build: .
    links:
      - tippecanoe
      - database
    command: >
      python manage.py run_import
    volumes:
      - "/mnt/vector_tiles:/app/vector_tiles"
      - "/tmp/geojson:/mnt/geojson"
