version: '3'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart

  tippecanoe:
    image: build.datapunt.amsterdam.nl:5000/datapunt/vector_tiles_tippecanoe
    user: root
    environment:
      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
    volumes:
      - "/mnt/tiles/vector_tiles:/vector_tiles"
      - "/mnt/geojson:/data_tiles"

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/vector_tiles_importer
    links:
      - tippecanoe
      - database
    command: >
      python manage.py run_import
    volumes:
      - "/mnt/geojson:/mnt/geojson"
