version: '3'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: basiskaart
    extra_hosts:
      admin.datapunt.amsterdam.nl: 10.99.157.24

  tippecanoe:
    image: repo.data.amsterdam.nl/datapunt/vector_tiles_tippecanoe
    user: root
    environment:
      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
    volumes:
      - "/mnt/tiles/vector_tiles:/vector_tiles"
      - "/mnt/geojson:/data_tiles"

  importer:
    image: repo.data.amsterdam.nl/datapunt/vector_tiles_importer
    links:
      - tippecanoe
      - database
    command: >
      python manage.py run_import
    volumes:
      - "/mnt/geojson:/mnt/geojson"
